title: aescanyo-blog
description: "Blog de Aescanyo"
author:
  name: "Antonio M. Escaño Arias"
  email: "al.antonio.escano.arias@iesportada.org"
  url: "https://aescanyo.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "aescanyo"
year : "2021"
